services:
  dpanel:
    image: dpanel/dpanel:latest
    container_name: dpanel
    restart: always
    ports:
      - "8807:8080"
    environment:
      APP_NAME: dpanel # 请保持此名称与 container_name 一致
      INSTALL_USERNAME: admin
      INSTALL_PASSWORD: admin
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/dpanel