services:
  etcd:
    image: bitnami/etcd:latest
    container_name: etcd
    restart: always
    volumes:
      - ./data:/etcd-data  # 持久化数据
      - ./conf/etcd.conf:/etc/etcd/etcd.conf  # 挂载配置文件
    environment:
      - ETCD_ADVERTISE_CLIENT_URLS=http://192.168.5.128:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ALLOW_NONE_AUTHENTICATION=yes
    ports:
      - "2379:2379"  # etcd 服务端口
    command: ["etcd", "--config-file=/etc/etcd/etcd.conf"]
    networks:
      - etcd-network

networks:
  etcd-network:
    driver: bridge
